const ACCESS_TOKEN_NAME = '__at';
const REFRESH_TOKEN_NAME = '__rt';
const SESSION_TOKEN_NAME = 'SESSION';

const ACCESS_TOKEN_EXPIRE = 15 * 60; // 15 minutes
const REFRESH_TOKEN_EXPIRE = 7 * 24 * 60 * 60; // 7 days

const SESSION_TOKEN_EXPIRE = 30 * 24 * 60 * 60; // 30 days

export {
  ACCESS_TOKEN_EXPIRE,
  REFRESH_TOKEN_EXPIRE,
  ACCESS_TOKEN_NAME,
  REFRESH_TOKEN_NAME,
  SESSION_TOKEN_NAME,
  SESSION_TOKEN_EXPIRE,
};
